version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/project
    container_name: url-short-nginx
    depends_on:
      - php-fpm
    restart: always
    ports:
      - "8088:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/project
    restart: always
    container_name: url-short-php-fpm
    depends_on:
      - postgres

  postgres:
    container_name: url-short-postgres
    image: postgres:12
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: secret
    ports:
        - "65432:5432"


  pgadmin:
      container_name: url-short-pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
      ports:
          - "5050:80"
      volumes:
          - ./docker/pgadmin:/var/lib/pgadmin


